language: nodejs

services:
  - docker

node_js:
  - "10"

branches:
  only:
  - master

install:
  - node --version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --pull --rm --tag hex0cter/nodejs-browsers:latest .
  - docker push hex0cter/nodejs-browsers:latest
  - rm -f $HOME/.docker/config.json
