language: node_js

services:
  - docker

node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"

branches:
  only:
  - master

script:
  - export NODEJS=$(node --version | sed 's/v//')
  - export LATEST_NODEJS=$(curl -s nodejs.org/dist/latest/SHASUMS256.txt | grep node- | cut -d '-' -f2 | head -1)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --pull --rm --build-arg NODEJS=${NODEJS} --tag hex0cter/nodejs-browsers:${NODEJS} .
  - docker push hex0cter/nodejs-browsers:${NODEJS}
  - if [[ "${LATEST_NODEJS}" == "${NODEJS}" ]]; then docker tag hex0cter/nodejs-browsers:${NODEJS} hex0cter/nodejs-browsers:latest && docker push hex0cter/nodejs-browsers:latest; fi
  - rm -f $HOME/.docker/config.json
